export enum Role {
    Manager = 'manager',
    Teacher = 'teacher',
    SubTeacher = 'sub_teacher',
    Student = 'student',
}

export const roles = {
    manager: [
            'view_users', 
            'view_cats',
            'view_crs', 
            'add_users_to_cat',
            'add_cat',
            'delete_users',         
            'delete_cat', 
            'update_users',
            'update_cat'
    ],
    teacher: [
        'view_students', 
        'view_crs',
        'add_student',
        'create_class',
        'update_class',
        'delete_class',
        'accept_connection_request',
        'send_message',
        'send_invite_request',
        'delete_message',
        'cancel_request',
        'send_request',
        'block_user',
        'unblock_user',
    ],
    sub_teacher: [
        'view_students', 
        'view_crs',
        'add_student',
        'create_class',
        'update_class',
        'delete_class',
        'accept_connection_request',
        'send_message',
        'send_invite_request',
        'delete_message',
        'cancel_request',
        'send_request',
        'block_user',
        'unblock_user',
    ],
    student: [
        'view_clrs',
        'view_sub__teachers',
        'update_own_profile',
        'send_connection_request',
        'accept_connection_request',
        'send_message',
        'send_join_request',
        'delete_message',
        'cancel_connection',
        'accept_request',
        'block_user',
        'unblock_user',
    ],
};